package com.dandelion.springTemplate;

import java.util.Date;
import java.util.UUID;

public class UserInfo {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column OoPassUserDev..tb_User.ID
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	private UUID ID;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column OoPassUserDev..tb_User.Alias
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	private String alias;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column OoPassUserDev..tb_User.Password
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column OoPassUserDev..tb_User.UserState
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	private Boolean userState;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column OoPassUserDev..tb_User.UserEmail
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	private String userEmail;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column OoPassUserDev..tb_User.LoginState
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	private Boolean loginState;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column OoPassUserDev..tb_User.IPAddress
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	private String IPAddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column OoPassUserDev..tb_User.CreatedDate
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	private Date createdDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column OoPassUserDev..tb_User.ModifiedDate
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	private Date modifiedDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column OoPassUserDev..tb_User.IsDeleted
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	private Boolean isDeleted;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column OoPassUserDev..tb_User.Birthday
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	private Date birthday;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column OoPassUserDev..tb_User.Gender
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	private Boolean gender;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column OoPassUserDev..tb_User.UserSignature
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	private String userSignature;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column OoPassUserDev..tb_User.AvatarIDFK
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */

	private int friendCount;
	private int fanCount;
	private int followCount;
	private int articleCount;
	private int registerFrom;
	private String BackgroundUrl;
	
	public String getBackgroundUrl() {
		return BackgroundUrl;
	}

	public void setBackgroundUrl(String backgroundUrl) {
		BackgroundUrl = backgroundUrl;
	}

	public int getRegisterFrom() {
		return registerFrom;
	}

	public void setRegisterFrom(int registerFrom) {
		this.registerFrom = registerFrom;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column OoPassUserDev..tb_User.ID
	 * 
	 * @return the value of OoPassUserDev..tb_User.ID
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public UUID getID() {
		return ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column OoPassUserDev..tb_User.ID
	 * 
	 * @param ID
	 *            the value for OoPassUserDev..tb_User.ID
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public void setID(UUID ID) {
		this.ID = ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column OoPassUserDev..tb_User.Alias
	 * 
	 * @return the value of OoPassUserDev..tb_User.Alias
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public String getAlias() {
		return alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column OoPassUserDev..tb_User.Alias
	 * 
	 * @param alias
	 *            the value for OoPassUserDev..tb_User.Alias
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public void setAlias(String alias) {
		this.alias = alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column OoPassUserDev..tb_User.Password
	 * 
	 * @return the value of OoPassUserDev..tb_User.Password
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column OoPassUserDev..tb_User.Password
	 * 
	 * @param password
	 *            the value for OoPassUserDev..tb_User.Password
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column OoPassUserDev..tb_User.UserState
	 * 
	 * @return the value of OoPassUserDev..tb_User.UserState
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public Boolean getUserState() {
		return userState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column OoPassUserDev..tb_User.UserState
	 * 
	 * @param userState
	 *            the value for OoPassUserDev..tb_User.UserState
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public void setUserState(Boolean userState) {
		this.userState = userState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column OoPassUserDev..tb_User.UserEmail
	 * 
	 * @return the value of OoPassUserDev..tb_User.UserEmail
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public String getUserEmail() {
		return userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column OoPassUserDev..tb_User.UserEmail
	 * 
	 * @param userEmail
	 *            the value for OoPassUserDev..tb_User.UserEmail
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column OoPassUserDev..tb_User.LoginState
	 * 
	 * @return the value of OoPassUserDev..tb_User.LoginState
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public Boolean getLoginState() {
		return loginState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column OoPassUserDev..tb_User.LoginState
	 * 
	 * @param loginState
	 *            the value for OoPassUserDev..tb_User.LoginState
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public void setLoginState(Boolean loginState) {
		this.loginState = loginState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column OoPassUserDev..tb_User.IPAddress
	 * 
	 * @return the value of OoPassUserDev..tb_User.IPAddress
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public String getIPAddress() {
		return IPAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column OoPassUserDev..tb_User.IPAddress
	 * 
	 * @param IPAddress
	 *            the value for OoPassUserDev..tb_User.IPAddress
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public void setIPAddress(String IPAddress) {
		this.IPAddress = IPAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column OoPassUserDev..tb_User.CreatedDate
	 * 
	 * @return the value of OoPassUserDev..tb_User.CreatedDate
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public Date getCreatedDate() {
		return createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column OoPassUserDev..tb_User.CreatedDate
	 * 
	 * @param createdDate
	 *            the value for OoPassUserDev..tb_User.CreatedDate
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column OoPassUserDev..tb_User.ModifiedDate
	 * 
	 * @return the value of OoPassUserDev..tb_User.ModifiedDate
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public Date getModifiedDate() {
		return modifiedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column OoPassUserDev..tb_User.ModifiedDate
	 * 
	 * @param modifiedDate
	 *            the value for OoPassUserDev..tb_User.ModifiedDate
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column OoPassUserDev..tb_User.IsDeleted
	 * 
	 * @return the value of OoPassUserDev..tb_User.IsDeleted
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column OoPassUserDev..tb_User.IsDeleted
	 * 
	 * @param isDeleted
	 *            the value for OoPassUserDev..tb_User.IsDeleted
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column OoPassUserDev..tb_User.Birthday
	 * 
	 * @return the value of OoPassUserDev..tb_User.Birthday
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column OoPassUserDev..tb_User.Birthday
	 * 
	 * @param birthday
	 *            the value for OoPassUserDev..tb_User.Birthday
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column OoPassUserDev..tb_User.Gender
	 * 
	 * @return the value of OoPassUserDev..tb_User.Gender
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public Boolean getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column OoPassUserDev..tb_User.Gender
	 * 
	 * @param gender
	 *            the value for OoPassUserDev..tb_User.Gender
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public void setGender(Boolean gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column OoPassUserDev..tb_User.UserSignature
	 * 
	 * @return the value of OoPassUserDev..tb_User.UserSignature
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public String getUserSignature() {
		return userSignature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column OoPassUserDev..tb_User.UserSignature
	 * 
	 * @param userSignature
	 *            the value for OoPassUserDev..tb_User.UserSignature
	 * 
	 * @mbggenerated Tue Nov 01 15:43:16 CST 2011
	 */
	public void setUserSignature(String userSignature) {
		this.userSignature = userSignature;
	}
	
	public int getFriendCount() {
		return friendCount;
	}

	public void setFriendCount(int friendCount) {
		this.friendCount = friendCount;
	}

	public int getFanCount() {
		return fanCount;
	}

	public void setFanCount(int fanCount) {
		this.fanCount = fanCount;
	}

	public int getFollowCount() {
		return followCount;
	}

	public void setFollowCount(int followCount) {
		this.followCount = followCount;
	}

	public int getArticleCount() {
		return articleCount;
	}

	public void setArticleCount(int articleCount) {
		this.articleCount = articleCount;
	}
	
}